[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
#
# [templates.cava]
# input_path = '~/.config/matugen/templates/cava-colors'
# output_path = '~/.config/cava/config'
#
# [templates.rofi]
# input_path = '~/.config/matugen/templates/rofi-colors.rasi'
# output_path = '~/.config/rofi/colors.rasi'
#
# [templates.kitty]
# input_path = '~/.config/matugen/templates/kitty-colors.conf'
# output_path = '~/.config/kitty/colors.conf'
# # post_hook = "kitty @ set-colors -a -c ~/.config/kitty/colors.conf"
#
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

# [templates.qt6ct]
# input_path = '~/.config/matugen/templates/qt-colors.conf'
# output_path = '~/.config/qt6ct/colors/matugen.conf'
#
# [templates.qt-colors]
# input_path = '~/.config/matugen/templates/QtColors.colors'
# output_path = '~/.local/share/color-schemes/Matugen.colors'
#
[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

# # [templates.ags]
# # input_path = '~/.config/matugen/templates/colors.scss'
# # output_path = '~/.config/ags/colors.scss'
#
# # [templates.shell]
# # input_path = '~/.config/matugen/templates/colors.scss'
# # output_path = '~/dotfiles/shell/colors.scss'
#
# [templates.ghostty]
# input_path = '~/.config/matugen/templates/ghostty.conf'
# output_path = '~/.config/ghostty/colors'
#
[templates.wezterm]
input_path = '~/.config/matugen/templates/wezterm.lua'
output_path = '~/.config/wezterm/colors.lua'

# [templates.chroma-shell]
# input_path = '~/.config/matugen/templates/colors.json'
# output_path = '~/.config/chroma/colors.json'

[templates.quickshell]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.config/quickshell/colors.json'
