add_newline = true

format = """\
$directory\
$python\
$nix_shell\
$rust\
$nodejs\
$fill\
$git_branch\
$git_status
$character\
"""

right_format = """\
$cmd_duration\
$time\
"""

[fill]
symbol = " "

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false
format = ' [$path]($style)[$read_only]($read_only_style) '

[python]
format = 'via [$symbol(${version} ($virtualenv))]($style)'
symbol = ' '

[nix_shell]
format = '[$symbol$state( \($name\))]($style)'
symbol = '❄️ '
style = 'bold blue'

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style)"

[git_status]
format = " [$all_status]($style) "

[character]
success_symbol = "[ ~>](bold green)"
error_symbol = "[ ~>](bold red)"
format = '$symbol '

[cmd_duration]
min_time = 1000
format = 'took [$duration]($style) '

