[config]

[templates.quickshell]
input_path = 'templates/colors.json'
output_path = '~/.config/quickshell/colors.json'

[templates.kitty]
input_path = 'templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.zellij]
input_path = 'templates/zellij.kdl'
output_path = '~/.config/zellij/themes/matugen.kdl'

[templates.yazi]
input_path = 'templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.gtk4]
input_path = 'templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.gtk3]
input_path = 'templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.kvantum_kvconfig]
input_path = 'templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = 'templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'


# [templates.niri]
# input_path = 'templates/niri-colors.kdl'
# output_path = '~/.config/niri/niri-colors.kdl'
